# Generated by Django 4.2.3 on 2024-02-22 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_real', models.IntegerField()),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('estimativa_tempo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('avaliacao', models.IntegerField()),
                ('execucao_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_service.execucaoservico')),
            ],
        ),
        migrations.AddField(
            model_name='execucaoservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_service.servico'),
        ),
    ]
