# Generated by Django 4.2.3 on 2024-02-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='execucao_servico',
        ),
    ]
